### ISSUE TITLE
Refreshed Orchestration token should still be valid.

### ISSUE THREAD

**Issue by pivnicek** [keboola/orchestrator-bundle#60]
When an orchestration token is refreshed it can not read the orchestration configuration anymore.  

![image](https://user-images.githubusercontent.com/569139/34642070-b1c31f86-f30d-11e7-91c5-593dae416e22.png)

**Comment by ErikZigo** [comment]
Do you have ID of the orchestration? It look like they/you refreshed orchestration token in "Storage/Tokens" section.

If you need refresh orchestration token, you should use Orchestrator API
https://keboolaorchestratorv2api.docs.apiary.io/#reference/orchestrations/refresh-orchestration-token/refresh-orchestration-token

(Encrypted token is stored also in orchestrator DB. Refresh token in Storage/Tokens will produce this error. Because orchestrator DB will contains still old token, not new one)

**Comment by ErikZigo** [comment]
I tried:
1) Create new orchestration
2) Refresh token via Orchestrator API

It looks ok.

**Comment by ErikZigo** [comment]
@pivnicek can I close this issue?

**Comment by pivnicek** [comment]
Maybe I should move it to connection.  Ideally I think that the token state should be consistent throughout connection.  I'll re-create the issue there.
